theme: minima
title: Another crack at academic leadership
author: Austen Rainer
email: a.rainer@qub.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  A draft site to explore how to present content for an academic leadership course.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
austenrainer:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
